### ISSUE TITLE
Replace all matrix operations with gl-matrix.

### ISSUE THREAD

**Issue by rosskettle** [gamelab/kiwi.js#10]

**Comment by BenjaminDRichards** [comment]
As of the v1.3.1 dev process, we've been unable to get gl-matrix to out-perform our own matrix code. As such I'm closing this issue. Good job, predecessors! You coded some very solid matrix code.

gl-matrix was previously used for computing cameras in the `GLRenderManager` code. I've removed it from v1.3.1, replacing it with our own matrix code. This allows us to remove the entire gl-matrix library, saving some download space (24KB, about 6.7% of the total size at the minified level), and eliminating some rare framework compatibility problems (see issue #136 ).
