### ISSUE TITLE
Spritesheet WITHOUT FILE EXSTENSION worked on local hosted game on Pc. But not when exported to Cocoonjs

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#106]

**Comment by BenjaminHarding** [comment]
Issue needs retesting on the 1.2 version of Kiwi. 

I think the problem was with creating blobs when using the XHR+arraybuffer method would not work as it was using the file extension. Now instead it uses the file type received. So I believe the issue should be resolved.
