### ISSUE TITLE
Timers do pause. But when the are resumed it acts like time has past normally.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#113]
I fixed this by adding a else if to the update of the timer.

/**
            * Internal update loop called by the Clock that this Timer belongs to.
            * @method update
            * @public
            */
            Timer.prototype.update = function () {
                if (this._isRunning && this._clock.elapsed() - this._timeLastCount >= this.delay && this._isPaused === false) {
                    this._currentCount++;

                    this.processEvents(Kiwi.Time.TimerEvent.TIMER_COUNT);

                    this._timeLastCount = this._clock.elapsed() || 0;

                    if (this.repeatCount !== -1 && this._currentCount >= this.repeatCount) {
                        this.stop();
                    }
                } else if(this._isPaused) {
                    this._timeLastCount = this._clock.elapsed() || 0;
                }
            };

**Comment by BenjaminDRichards** [comment]
Issue resolved.

The proposed fix would essentially restart the timer from the start of its current cycle when paused.

My fix goes a little further and makes it compatible with better clocks. It tracks time difference between updates for fully precise timing.

https://github.com/gamelab/kiwi.js/commit/1c4e86e154367df9af66982db29f0f62451c3afd
