### ISSUE TITLE
Robust debug mode

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#117]
We should create `Kiwi.log`, which checks for debug mode, and if found, sends its parameters to `console.log`. This will allow us to deactivate debug mode completely and run with a clean console.

**Comment by BenjaminHarding** [comment]
@BenjaminDRichards we now have it in 1.2! 

Sadly it doesn't check for 'debug' mode (open to discussion/future change) because users can set the features themselves at the creation stage.

Also has this nifty recording and tagging system. I already love using it :)
