### ISSUE TITLE
Investigate color conversion utilities

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#120]
Kiwi.Utils should have some color conversion systems. (And maybe other conversions?)

Assume a normalized color space going forward. (Maybe a color object?) Additional color systems include:
* Web mode colors (range 0-255)
* HSB colors (what's the standard format? Is it 360,100,100?)
* Hex colors (#ffffff)

**Comment by BenjaminHarding** [comment]
Implemented in 1.2.0! Woop woop!
