### ISSUE TITLE
LineSegmentToRectangle is not working correctly

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#124]
The lineToRawSegment is checking this:

if ((output.x <= maxX && output.x >= minX) === true || (output.y <= maxY && output.y >= minY) === true)

if should be changed to if ((output.x <= maxX && output.x >= minX) === true &&  (output.y <= maxY && output.y >= minY) === true)

'&&' not '||'. The current setup means that just one of the bounds needs to be correct for a IntersectResult result to be equal to true.

**Comment by BenjaminDRichards** [comment]
Fixed in issue #166
