### ISSUE TITLE
Game prints 'Stage specified' even if no stage was specified.

### ISSUE THREAD

**Issue by RaniSputnik** [gamelab/kiwi.js#129]
The console print is incorrect and that is annoying when debugging.
"Kiwi.Game: Stage specified, but is not a valid option. Set to NONE." is printed even if no stage is specified. It should print, "Kiwi.Game: Stage scaling not specified, defaulting to NONE." and "Kiwi.Game: Stage scaling specified, but {value} is not a valid option. Set to NONE." as error text.

**Comment by BenjaminHarding** [comment]
@RaniSputnik Updated it in the latest version thanks! 
Turns out it was due to an incorrect conditional which always evaluated to true. Doh
