### ISSUE TITLE
Game domParent parameter should be more permissive

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#131]
Currently it uses `document.getElementById', which means you have to use `id` and can't pass actual DOM elements or use a `class`.

**Comment by BenjaminHarding** [comment]
The system now attempts to get an element using 'document.querySelector' first. If no element is found it then reverts to using 'document.getElementById'. 

This enables users to now use CSS style selectors to select the element that the game should be added to whilst maintaining current functionality :D
