### ISSUE TITLE
When Audio object has been paused AND resumed looping no longer works. 

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#132]
Potential fix ideas:

Looking at the Audio Kiwi.Sound.Audio it looks like the problem might be with the conditions that the game loops. 

This is inside of the update loop. The game checks if the ideal time finished is > current time. I think the resume does not correctly adjust the 'start time' time. Thus causing problems.

**Comment by BenjaminHarding** [comment]
This should now be fixed in the latest 1.2 version. The issue was that looping wasn't being set on the buffersource when the audio was resumed, and so it would play resume but not loop again.
