### ISSUE TITLE
Add favicon to website

### ISSUE THREAD

**Issue by GloverDonovan** [gamelab/kiwi.js#145]
I propose that a favicon be added to the main website ( http://www.kiwijs.org/ ).

**Comment by BenjaminHarding** [comment]
I second this proposal ;)

**Comment by GoToLoop** [comment]
It's so rare to find sites which got no favicon! Please make 1 ASAP!  :P

**Comment by danmilward** [comment]
Agreed :)

**Comment by thornyd** [comment]
Here's a preview of 8 different KiwiJS favicons:
![kiwi-favicons](https://cloud.githubusercontent.com/assets/1079101/5893996/6073dc5c-a55d-11e4-8254-139fc25cd223.jpg)

And here's the individual icons:

![kiwi-favicon-1](https://cloud.githubusercontent.com/assets/1079101/5894001/7b0de6c0-a55d-11e4-88d8-789734f9ded6.png)
![kiwi-favicon-2](https://cloud.githubusercontent.com/assets/1079101/5894000/7b0c6e9e-a55d-11e4-9a56-8d03d13f307e.png)
![kiwi-favicon-3](https://cloud.githubusercontent.com/assets/1079101/5894006/7b712834-a55d-11e4-8ef3-73a83fb0bcbc.png)
![kiwi-favicon-4](https://cloud.githubusercontent.com/assets/1079101/5894007/7b785f0a-a55d-11e4-8985-ec4bce287ae5.png)
![kiwi-favicon-5](https://cloud.githubusercontent.com/assets/1079101/5894005/7b624fc6-a55d-11e4-966f-5905f5a0ff11.png)
![kiwi-favicon-6](https://cloud.githubusercontent.com/assets/1079101/5894004/7b5fd250-a55d-11e4-9074-71e716711b02.png)
![kiwi-favicon-7](https://cloud.githubusercontent.com/assets/1079101/5894002/7b348f50-a55d-11e4-9853-6df3230981f2.png)
![kiwi-favicon-8](https://cloud.githubusercontent.com/assets/1079101/5894003/7b3650ec-a55d-11e4-927d-08f05fe07859.png)

**Comment by BenjaminHarding** [comment]
Very nice @thornyd! I be thinking the transparent Kiwi (also known as Kiwi Icon #6) looks the best. Do we have any other recommendations.

**Comment by GloverDonovan** [comment]
I prefer the black outline on kiwi-favicon-3 :+1:

**Comment by zacharyf1991** [comment]
I'm thinking the last one ( all dark blue ). It's sleek.

**Comment by danmilward** [comment]
I like #6 and #8... I'd probably go with #8 since Zach thinks its sleek :)
Any other opinions?



On Mon, Jan 26, 2015 at 2:49 PM, Zachary W. Freiberg <
notifications@github.com> wrote:

> I'm thinking the last one ( all dark blue ). It's sleek.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gamelab/kiwi.js/issues/145#issuecomment-71405702>.
>



-- 

Dan Milward

M +64 21 449 901

178 Willis Street – Wellington CBD – Wellington 6011 – New Zealand
www.kiwijs.org  -  www.gamefroot.com <http://www.gamefroot.com/leveleditor>

**Comment by BenjaminHarding** [comment]
The black bird has been placed on the site since it seems it has the majority. Checks it out! 
Thanks @GloverDonovan that :)

**Comment by GloverDonovan** [comment]
Cool :smile:
