### ISSUE TITLE
SCALE_FIT is inaccurate when scaling down

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#147]
Cerebral Fix reports as follows:

> Daniel Scott-Weekly
10:06 AM
Hey, I am having an issue with using a scale type of SCALE_FIT. I have my canvas drawn to 1920x1080 but when playing on a 1366x768 window my height is scalled to 758.8125px when I guess it should be 768.3749999999999. This isn't just limited to this scale, another example which should round to an exact number is 1680x1050 when playing on 1280x800 screen ends up with a height of 789.375px. Actually it seems happen with all of the scales down. However when scaling up from 1280x720 to 1920x1080 it is fine.
GameLab Ltd
12:01 PM
Thanks for that; I'll investigate the issue. Some clarifications: Are you using a browser? Are you using WebGL, Canvas, or default (WebGL) rendering?
Joel Mason
12:02 PM
Chrome 39, WEB_GL
Daniel Scott-Weekly
12:04 PM
Same thing happens with our node web kits builds which uses chromium anyway so I didn't really expect any change.
Daniel Scott-Weekly
12:07 PM
Weird in firefox 34.0.5, with a canvas size of 1920x1080 it has a height of 1070.44px
Daniel Scott-Weekly
12:08 PM
Same with firefox 35.0

**Comment by BenjaminHarding** [comment]
Temporary fix added until a Scale Manager is implemented. See issue #148 for further details.
