### ISSUE TITLE
Kiwi.Log tag channel filters

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#151]
It would be nice to be able to set only certain channels to show in Kiwi.Log; to mask a tag or to mask all but a certain set of tags.

**Comment by BenjaminHarding** [comment]
You can now filter out messages by tag in Kiwi.Log in version 1.3.0. 

###How it works. 
Any messages that do not contain the same tags that are in the filters will not be shown in the console. They will still be recorded though. 

By default Kiwi.Log does not contain any filters. 

You can add and remove filters by using the `addFilter` and `removeFilter` methods. 

Alternatively you can access the `tagFilters` array to add/remove filters.
