### ISSUE TITLE
Kiwi.HUD.Widget.MenuItem API Doc does not have a constructor. 

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#154]
This API docs say that it extends Kiwi.HUD.Widget.Button. I do not know if it is meant to have a constructor or not.

**Comment by BenjaminDRichards** [comment]
It should, but did not, have a `constructor`. What it did have was a `contructor`, which I can only assume is a robot in disguise waiting to ambush the Autobots.

I have eliminated the Decepticon menace. Our documentation is safe.
