### ISSUE TITLE
API Docs for Kiwi.GameObjects.Textfield not showing.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#155]
Unable to access 'Kiwi.GameObjects.Textfield' because it automatically selects 'Kiwi.GameObjects.TextField'. Therefore unable to see constructor for Kiwi.GameObjects.Textfield and Kiwi.GameObjects.TextField requires seeing it.

**Comment by BenjaminDRichards** [comment]
Removed documentation for lowercase `Textfield` altogether, as it was confusing YuiDocs. Uppercase `TextField` now has a note about the alias.
