### ISSUE TITLE
Consistency between filetypes.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#156]
Json files and audio files should be accessed the same way as textures. Potentially vice versa as well.

**Comment by zacharyf1991** [comment]
e.g. 

state.preload = function () {
    this.addJSON('tilemap', './assets/img/tiles/tilemap-json.json');
    this.addSpriteSheet( 'tiles', './assets/img/tiles/tileset-basic.png', 48, 48 );
};

state.create = function () {
	this.tilemap = new Kiwi.GameObjects.Tilemap.TileMap(this, 'tilemap', this.textures.tiles);

	this.addChild(this.tilemap.layers[0]);
	this.addChild(this.tilemap.layers[1]);
};

**Comment by BenjaminHarding** [comment]
This functionality has been added in to the dev 1.3.0 branch! Textures can now be passed by their key added and Audio/Data can be passed like textures currently are.

```
 //Current Method Pre 1.3
this.music = new Kiwi.Sound.Audio(this.game, 'music', 1, true);
this.player = new Kiwi.GameObjects.Sprite(this, this.textures.player, 275, 150);

 //In 1.3
this.music = new Kiwi.Sound.Audio(this.game, this.audio.music, 1, true);
this.player = new Kiwi.GameObjects.Sprite(this, 'player', 275, 150);
```
