### ISSUE TITLE
Animation update is not validating the frameindex

### ISSUE THREAD

**Issue by rydairegames** [gamelab/kiwi.js#159]
In Animation.prototype.update, the frameindex is not being validated before it is updated. This causes problems with single frame, non-looping animations, because frameindex will be set to something other than 0 and this._parent.updateCellIndex is still called resulting in an error.

**Comment by BenjaminHarding** [comment]
Thanks for that. The animation problem have been addressed in 1.2.1.

Issues #149 and #150

**Comment by rydairegames** [comment]
Awesome, I'll be sure to check the closed issues next time!
