### ISSUE TITLE
Potentially adding new function to TileMapLayer to get a Tile when you already know the index

### ISSUE THREAD

**Issue by rydairegames** [gamelab/kiwi.js#160]
I added this in because it was useful for me (I think of my map in terms of rows and cols, not x and y), plus there is already a similar function to set a tile by the index. 

TileMapLayer.prototype.getTileFromIndex = function (t){
      return (t !== -1) ? this.tilemap.tileTypes[this._data[t]] : null;
}

**Comment by BenjaminHarding** [comment]
Thanks for that @rydairegames  Always interesting in how other people think of things like this. 

Will have a look into adding it for 1.3.0 :)

**Comment by BenjaminHarding** [comment]
Added in the 1.3.0 branch :)
