### ISSUE TITLE
Kiwi.Geom.Line.perp method is not working correctly.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#167]
When attempting to see if a circle was intersecting a line I used the Kiwi.Geom.Intersect.lineToCircle method.

This checks the length of the line perpendicular to the circle x, y pos length and sees if it is length is less than the radius of the circle.

The algorithm error either occurs in the Kiwi.Geom.Line.perp method OR in the Kiwi.Geom.Line.intersectLineLine method which is called by the perp method. 

The intersectResult of the Kiwi.Geom.Intersect.lineToCircle check always returns false. Therefore the lines length is apparently never shorter than the radius. This could potentially be a problem with the Kiwi.Geom.Line.length property. 

Upon investigation of the length property I very much doubt that it is the problem.

**Comment by zacharyf1991** [comment]
You can see an example of this not working is in the example repo. It will not be displayed on the main page but the files will be visible inside of the 'geom' folder. To enable them you can do this from the kwi-example-main.js file inside of the 'kiwi-examples/examples/_site/js/' folder. See line 43.

**Comment by BenjaminDRichards** [comment]
Fixed; see #166 for details.
