### ISSUE TITLE
API Docs Copy Paste Error

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#169]
Kiwi.Geom.LineSegmentToCircle should be Kiwi.Geom.LineSegmentToRectangle for one of the entries.

**Comment by zacharyf1991** [comment]
Kiwi.Geom.Intersect.lineSegmentToCircle *

**Comment by BenjaminHarding** [comment]
Had a look at the Intersect class and could not find the issue specified. Closing Issue.
