### ISSUE TITLE
Missing rayToCircle intersection from Kiwi.Geom.Intersect object.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#170]

**Comment by BenjaminDRichards** [comment]
I've implemented this for the v1.3.1 branch, which is looking more and more like a 1.4. Semver requires new features to go in minor releases.

I've also converted `Ray` to be an extended `Line`, which makes it more flexible and actually reduces code size somewhat. In future major releases we may wish to deprecate `Ray` altogether in favour of a more flexible `Line`.
