### ISSUE TITLE
Kiwi.Geom.lineToLineSegment does not work correctly.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#172]
Kiwi.Geom.Intersect.lineToLineSegment does not work as intended. Look in example repo for an example of what is happening

**Comment by BenjaminDRichards** [comment]
A simple fix: `lineToLineSegment` was checking whether the intersect point was within the X OR Y range of the segment. It should have been AND. `lineSegmentToLineSegment` relies on `lineToLineSegment`, so this fix also makes it work properly (see issue #171).
