### ISSUE TITLE
Clock.prototype.start doesn't "reset the clock" with respect to elapsed()

### ISSUE THREAD

**Issue by rydairegames** [gamelab/kiwi.js#177]
Since the elapsed function now just returns this._elapsed (instead of computing it as before), calling the start method on a clock doesn't change the returned value of the elapsed function. 

My use case is enforcing a minimum amount of time between some user-generated events. When the event is called, I reset the clock by calling myClock.start(). Then before the event is called again, I check myClock.elapsed(). 

My fix was to add this._elapsed = 0; into the start function, but I haven't thought through any other ways of using the elapsed function, so it's probably not a quick fix except for me.

**Comment by BenjaminDRichards** [comment]
The `start()` function should indeed reset elapsed time. In fact, elapsed time should be 0 on the frame in which a reset occurs. In `start()`, I've added `_elapsed=0` and reset `_lastMasterElapsed` and `_currentMasterElapsed` to the master, which results in the desired behavior.
