### ISSUE TITLE
Stage rgbColor property

### ISSUE THREAD

**Issue by BenjaminHarding** [gamelab/kiwi.js#198]
rgb color property on the state doesn't set the correct colour when a channel is set to 0

**Comment by BenjaminHarding** [comment]
Update: After a little more investigation the issue is with the Colour Utils, as it also effect the other colour systems where it is used. 

The problem is with the detection between normalized values and values ranging from 0 - 255.

**Comment by BenjaminDRichards** [comment]
I've fixed the normalised/255 issue by forcing everything to the 0-255 range. This range is specified by the Stage API, so that's what should happen anyway.
