### ISSUE TITLE
Not Enough Arguments, Unlocking Audio iOS

### ISSUE THREAD

**Issue by RaniSputnik** [gamelab/kiwi.js#203]
There is an issue with the AudioManagers._unlocked method on iOS, when calling the following code the Safari inspector throws an error "Not Enough Arguments";

    this._unlockedSource.start();

This was tested in a WebView using Cordova but I imagine will occur when navigating to a site with a Kiwi game present also.

**Comment by BenjaminHarding** [comment]
Thanks :) Fixed the issue by passing an argument.
