### ISSUE TITLE
Audio doesn't loop in Web Audio when there isn't a marker

### ISSUE THREAD

**Issue by rydairegames** [gamelab/kiwi.js#207]
When using web audio, looping doesn't work when a marker isn't set, because this.play(this._currentMarker, true) doesn't get called when this._currentMarker is 'default'. 

My fix was to just add this.play(this._currentMarker, true) add the end of the if (this._currentMarker == 'default') block in Audio.prototype.update.

**Comment by BenjaminHarding** [comment]
Thanks @rydairegames. These bugs have been addressed in version 1.3.1 :)

Ended up removing the 'default' check, as it is unnecessary. While at it we also cleaned up using a more standard method of looping between the different sound methods.
