### ISSUE TITLE
The way to define d.ts file, in the class under the Kiwi.Plugins.

### ISSUE THREAD

**Issue by tkyaji** [gamelab/kiwi.js#208]
I tried to make ".d.ts" file of plugin, but it was a compile error.
For example following plugin.

```typescript
/// <reference path="kiwi.d.ts" />

declare module Kiwi.Plugins {
    class SamplePlugin {
    }
}
```

The cause of the compile error is the following code in Kiwi.ts.

```typescript
export var Plugins = {};
```

How is next code?
```typescript
// export var Plugins = {};
export class Plugins {}
```
or
```typescript
// export var Plugins = {};
export module Plugins {null;}
```

**Comment by BenjaminHarding** [comment]
Thanks for that @tkyaji 

We have not been using much typescript with the games we have made lately, so we never ran across this issue. 

Decided to implemented your second suggestion, since the Kiwi.Plugins is a wrapper for multiple plugins.
