### ISSUE TITLE
touch events not working correctly on IE11.

### ISSUE THREAD

**Issue by benliddicott** [gamelab/kiwi.js#212]
I have a patch for this:

From 6c664c3ae852962b007f05a8513f7013318505d7 Mon Sep 17 00:00:00 2001
From: benliddicott <ben@beetlesoft.co.uk>
Date: Tue, 23 Jun 2015 12:56:19 +0100
Subject: [PATCH 2/2] Fix touch on IE11 Windows 8.1

---
 src/input/Touch.ts | 22 ++++++++++++++--------
 1 file changed, 14 insertions(+), 8 deletions(-)

diff --git a/src/input/Touch.ts b/src/input/Touch.ts
index 20bd9df..a975486 100644
--- a/src/input/Touch.ts
+++ b/src/input/Touch.ts
@@ -297,7 +297,10 @@ module Kiwi.Input {
 							pointerMove = 'pointermove';
 
                         //Is it IE 10?
-						if ((window.navigator.msPointerEnabled)) {
+                        if (window["PointerEvent"]) {
+                            // IE11 - Use standard event names
+                        } else if ((window["MSPointerEvent"])) {
+                            // IE10 compatibility
 							var pointerUp = 'MSPointerUp',
 								pointerDown = 'MSPointerDown',
 								pointerEnter = 'MSPointerEnter',
@@ -692,7 +695,7 @@ module Kiwi.Input {
 		* @private
 		*/
 		private onPointerStart(event: MSPointerEvent) {
-			if (event.type === 'touch') {
+            if (event.type === 'touch' || event.type === "pointerdown") {
 				this._registerFinger(event, event.pointerId);
 			}
 		}
@@ -704,7 +707,7 @@ module Kiwi.Input {
 		* @private
 		*/
 		private onPointerCancel(event: MSPointerEvent) {
-			if (event.type === 'touch') {
+            if (event.type === 'touch' || event.type === "pointercancel") {
 				this._cancelFinger(event, event.pointerId);
 			}
 		}
@@ -716,7 +719,7 @@ module Kiwi.Input {
 		* @private
 		*/
 		private onPointerEnter(event: MSPointerEvent) {
-			if (event.type === 'touch') {
+            if (event.type === 'touch' || event.type === "pointerenter") {
 				this._enterFinger(event, event.pointerId);
 			}
 		}
@@ -728,7 +731,7 @@ module Kiwi.Input {
 		* @private
 		*/
 		private onPointerLeave(event: MSPointerEvent) {
-			if (event.type === 'touch') {
+            if (event.type === 'touch' || event.type === "pointerleave") {
 				this._leaveFinger(event, event.pointerId);
 			}
 		}
@@ -739,7 +742,7 @@ module Kiwi.Input {
 		* @param event {PointerEvent}
 		*/
 		private onPointerMove(event: MSPointerEvent) {
-			if (event.type === 'touch') {
+            if (event.type === 'touch' || event.type === "pointermove") {
 				this._moveFinger(event, event.pointerId);
 			}
 		}
@@ -751,7 +754,7 @@ module Kiwi.Input {
 		* @private
 		*/
 		private onPointerEnd(event: MSPointerEvent) {
-			if (event.type === 'touch') {
+            if (event.type === 'touch' || event.type === "pointerup") {
 				this._deregisterFinger(event, event.pointerId);
 			}
 		}
@@ -803,7 +806,10 @@ module Kiwi.Input {
                         pointerMove = 'pointermove';
 
                     //Is it IE 10?
-                    if ((window.navigator.msPointerEnabled)) {
+                    if (window["PointerEvent"]) {
+                        // IE11 - Use standard event names
+                    } else if ((window["MSPointerEvent"])) {
+                        // IE10 compatibility
                         var pointerUp = 'MSPointerUp',
                             pointerDown = 'MSPointerDown',
                             pointerEnter = 'MSPointerEnter',
-- 
1.9.5.msysgit.0

**Comment by benliddicott** [comment]
OK well I don't know how to send you a patch file!

**Comment by benliddicott** [comment]
I guess I could fork and send you a pull request? Would that be better?

**Comment by BenjaminHarding** [comment]
@benliddicott Fork and a pull request would be the best thanks!

**Comment by benliddicott** [comment]
Done the f&pr.

**Comment by BenjaminHarding** [comment]
Thanks for that! Will look into soon :)
