### ISSUE TITLE
iOS scrolling issue

### ISSUE THREAD

**Issue by jithujose** [gamelab/kiwi.js#221]
Hi,

When I include the MatchThreeGame example without an iframe into a long page, scrolling stops working when the game gets loaded.

How can I fix this issue?
Thanks!

**Comment by BenjaminHarding** [comment]
Mouse scroll is disabled when the users cursor is over the game by default.
To enable scrolling you can set `preventWheel` to `false` on the cursor object.

```
game.input.mouse.cursor.preventWheel = false;
```
