### ISSUE TITLE
Error on ios safari when Audio format not supported

### ISSUE THREAD

**Issue by rydairegames** [gamelab/kiwi.js#223]
Games played in mobile safari will break if a sound format is not supported after the first touch event. 

When adding an unsupported audio file to a State using addAudio, Kiwi logs an error and doesn't add the audio file to the fileStore. Then when an Audio object is created, Kiwi checks to see whether the name of the audio file exists in the fileStore. If it doesn't exist, then Kiwi logs out 'Could not play Audio...', but the audio object is still registered on the AudioManager.

This is ok in Safari, but on ios, a touch event causes the audio to unlock, which tries to ._setAudio on each of the audio objects in the audiomanager's ._sounds array.  The attempt to get the audio file from the fileStore then causes the error. 

TypeError: undefined is not an object (evaluating 'this._file.data')
_setAudio kiwi.js:29067
set kiwi.js:29026
update kiwi.js:28864
...

Having the audio file in the supported format as well makes this problem go away, but maybe the audio object should be unregistered from the audio manager if it doesn't have its file in the fileStore.

**Comment by BenjaminHarding** [comment]
@rydairegames Thanks for the detailed response. Will investigate this on the devices we have in the office :)

**Comment by BenjaminHarding** [comment]
Fixed this bug by adding in an additional `supported`property to the Audio Object. `Supported` is simply a flag to indicate if the file was found on the filestore when it was created. 

Removing unsupported audio files as suggested by @rydairegames also sounds like a great idea, but brings a question of whether it should be automatically destroyed or not. Will definitely think about this in the future.
