### ISSUE TITLE
Multi-Texture Plugin

### ISSUE THREAD

**Issue by arcanis** [gamelab/kiwi.js#228]
Hi,

This issue is more a question than anything: in the [following blog post](http://www.kiwijs.org/2014/09/new-webgl-shader-system-kiwi-js-v1-1-0/#multi-texture-atlas) from 2014, you talk about a multi-texture plugin. I've looked for a followup, but unfortunately haven't been able to find anything on the subject. Is is still required to manually implement the MultiTextureAtlas?

If it the plugin isn't released yet,

> Try not to do things this way – it will save you time and worry in the long term.

What is the correct way to do it?

Thanks,

**Comment by arcanis** [comment]
I've found the following file by accident : [MultiTexture-1.0.0.js](https://raw.githubusercontent.com/gamelab/UberShader-Plugin/master/lib/MultiTexture-1.0.0.js)

I'll try to use it in the meantime, but maybe it should be in a separate repository, don't you think?

**Comment by BenjaminDRichards** [comment]
@arcanis Good catch. I've actually been polishing up a version of the MultiTextureAtlas plugin for release; it's part of developing a new plugin that I'm quite excited about. Unfortunately, that one's not ready yet, and I'm holding off on finalising the MTA until I know it plays well with the new plugin. I'd rather not put out something that isn't actually useful.

This will probably happen in the next few weeks, once we're done with our summer break :) For now I'll close this issue pending the upcoming releases.
