### ISSUE TITLE
Camera matrix transformation anchor point too dominant when rotating

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#235]
I'm surprised this hasn't been noticed beforehand. Cameras seem to rotate around their anchor point - but the anchor point doesn't move with the camera.

Thus, if the camera is moved along X and rotated, it will appear to move up and down along Y. This is counterintuitive.

This is due to something in the way the camera matrix is computed. Geometry appears to be fine, but cameras are parentless and do some things literally backwards, so there is definitely a confusion in there.

**Comment by BenjaminDRichards** [comment]
Cameras fixed. I'm using this basic philosophy for both WebGL and Canvas rendering:
- Set a scratch matrix with zero translation but other transform properties of the camera;
- Append a translation operation.

This is definitely more efficient. For WebGL rendering, where the original op would call `identity()`, `getConcatenatedMatrix()`, `prepend()`, and `translate()`. The new op calls `setFromOffsetTransform()` (which is part of the concat process anyway), and `append()`. A significant savings.

The canvas version is also slightly nicer; it's substituted a `setFromOffsetTransform` for a `getConcatenatedMatrix`.

All tests are thus far positive, so I think this is a win.

**Comment by BenjaminHarding** [comment]
Woop woop! Nice work.
