### ISSUE TITLE
TextField doesn't accept arrays as color parameters

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#249]
In most cases, `TextField.color` supports array setting, e.g. `color = [ 0.7, 0, 0 ];`. But this doesn't work as a parameter.

This is because the constructor just passes the parameter to a `Kiwi.Utils.Color` constructor, but that doesn't support arrays. `TextField.color` is a setter which uses `Color.set.apply` to break down arrays.

Fix: use the setter in the constructor.

Thanks to Robert Wildling for pointing this out.

**Comment by rowild** [comment]
Thank you for filing and taking care. (And for my fantastic name :-) ... )

**Comment by BenjaminDRichards** [comment]
Uh, I might not be 100% awake yet :)

  Wildman -> Wildling

**Comment by BenjaminDRichards** [comment]
This issue has been resolved, along with an overhaul of TextField documentation.
