### ISSUE TITLE
kiwijs.org is Suspended

### ISSUE THREAD

**Issue by Diuda** [gamelab/kiwi.js#289]
The official website kiwijs.org has been down for 3 days now and it shows that the account has been suspended. I need the documentation available on the official website. 
![screenshot from 2017-09-01 11-22-29](https://user-images.githubusercontent.com/12708871/29956914-e10554d6-8f07-11e7-8d13-06925c82406d.png)

**Comment by BenjaminDRichards** [comment]
So do we! We've got the site back up now. Some wires got crossed somewhere.

Closing this as resolved, but worth thinking about a couple of issues:

* There's no harm in duplicate information. www.kiwijs.org is still the official front line, but we do have a (completely empty) wiki here on Github. That could easily be populated.
* Some information is available in the repo itself: http://www.kiwijs.org/api/ is itself a copy of the `docs/` folder. This is only the technical documentation, and contains none of the examples, step-by-step tutorials, or other resources from the main page; but it's still a very useful resource.
