### ISSUE TITLE
release update?

### ISSUE THREAD

**Issue by rowild** [gamelab/kiwi.js#292]
Some time ago - actually way over a year - it was mentioned that there would be a release-update fixing the one and other issue. Nothing has happened so far. 

Are there any plans for auch a thing?

Thanks for the info!

**Comment by BenjaminDRichards** [comment]
Happy New Year! Unfortunately, due to limited internal resources, we've been unable to finalise a release. But I don't think we can put it off much longer, as all the projects taking up our time use KiwiJS. I really can't promise anything, because we're stretched incredibly tight. Anybody willing to contribute to the 1.5.0 branch is very welcome, of course!

**Comment by rowild** [comment]
A happy new year to you, too, Ben!
The answer is of course the one I expected. Which is a bit sad, because around 2 years ago it was the same answer. I of course do understand you up to some degree, but when it comes to the framework and its reputation, it just doesn't do any good. Other frameworks release on a regular basis and fix bugs that way. And from what I see there is enough "material" here, too, to have had 3 more (minor) releases at least.
And that makes me a bit sad since I spend a lot of time with it and hoped that there would be at least minor releases coming up - which would have been motivating... (I am not in the business of gaming, but whenever I find some time I like to give it a try, and KiwiJS is my number one framework-to-go...)
To be honest: I do not really see the reason why there is not minor release at least. Some things have been fixed over the last two years, from what I see. So why not kick out a minor release after e.g. 5 bug fixes? Along with a change log...? I assume that would bring more attention to the people and eventually more contributors. I know of framework and CMSs that kick out a release after even 1 minor (!) bug fix. What developers see is that there is a constant "heart beat" driving the project...
Well... no need to tell you things like that, you most certainly know them better than I do. I just hope that KiwiJS is not dead... that would make me very sad... because, for some reason I have the feeling that KiwiJS is the "friendliest" gaming framework out there. Not code-wise (or maybe even that), but certainly when it comes to "character"... must be the developers behind Kiwi... ;-)

**Comment by danmilward** [comment]
Howdy @rowild I'm Dan from the Gamefroot / Kiwi crew. Thanks for your kind words and Happy New Year. 

Oddly enough I like to think that we're the "friendlisest" framework out there too ;-)

Unfortunately even when we were pushing out frequent updates and releasing plugins regularly we could not seem to capture the hearts and minds of the developer masses. That being the case we've had to focus on Kiwi features that support making our product Gamefroot better. So I think you can expect to see a major update from us with all these features / improvements in a month or two.  

After that the future is not clear to me. The only way I can see things changing is if we do something vastly different from other frameworks that allows us a point of different in which we can thrive and build a community around. AI? VR? AR?

I'm not sure. It IS sad that we have spent all this time and effort making things better and have not been able to make that easily available, but like Ben says, it's particularly tricky when you're a small team. So if you or anybody reading this wants to help or has any ideas I'd love to chat :)

dan@gamefroot.com

**Comment by BenjaminDRichards** [comment]
A month or two, hmm? I'm looking forward to it - been spending far too long on my other 8 or so development roles.

As for a point of difference, my suggestion is simply what we've been doing all along: education. Gamefroot is education, and KiwiJS is the backbone of Gamefroot. Once our Gamefroot curriculum is mature, it makes sense to me that we'd move on to a KiwiJS curriculum. It's a natural evolution from visual coding into real coding. That certainly won't hurt user friendliness!
